---
output: 
  html_document:
    code_folding: hide
css: styles.css
---

# Land use changes {.tabset}
  
```{r setup, message = F, warning = F, results = 'hide', echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, echo = T, fig.path = 'figs/', dev.args = list(family = 'serif'), fig.path = 'figures/')

library(tidyverse)
library(forcats)
library(foreign)
library(reactable)
library(here)
library(networkD3)

data(acresjso)
dat <- acresjso

source('R/funcs.R')

# # style file
# styles <- readLines('https://raw.githubusercontent.com/tbep-tech/css-styling/master/styles.css')
# writeLines(styles, 'styles.css')
```

Values in each table are acreage, unless noted otherwise. 

## Descriptor

```{r}
# format results
sums <- dat %>%
  filter(var %in% 'HMPU_DESCRIPTOR') %>% 
  select(-var) %>% 
  spread(name, areaac, fill = NA) %>% 
  mutate(
    grpval = case_when(
      val %in% c('Mangrove_Swamps', 'Salt_Marshes', 'Salt_Barrens') ~ 'Tidal Wetlands', 
      val %in% c('Streams_and_Waterways', 'Lakes', 'Wetland_Hardwood_Forests','Wetland_Coniferous_Forests', 'Wetland_Forested_Mixed',  'Vegetated_Non-Forested_Wetlands') ~ 'Freshwater Wetlands', 
      val %in% c('Dry_Prairie', 'Shrub_and_Brushland', 'Mixed_Rangeland', 'Upland_Coniferous_Forest', 'Upland_Hardwood_Forest') ~ 'Native Uplands',
      val %in% c('Restorable_Agriculture', 'Restorable_Developed', 'Restorable_Mining', 'Restorable_Shoreline', 'Restorable_Pond') ~ 'Opportunity Areas', 
      val %in% c('Lakes_Reservoirs', 'Developed') ~ 'Developed'
    ), 
    chg = `2017` - `1990`,
    chgper = 100 * (`2017` - `1990`) / `1990`
  )

rct_fun(sums, 'Habitat')
```

```{r}
chgdat <- read.dbf('T:/05_GIS/HMPU/comp1990v2017/TBEP_dbasinsg_LU9017.dbf')
lkup <- read.csv('data-raw/FLUCCShabsclass.csv')

clp <- lkup %>% 
  select(HMPU_DESCRIPTOR, FLUCCSCODE) %>% 
  group_by(HMPU_DESCRIPTOR) %>%
  deframe() %>%
  map(as.character)
 
sumdat <- chgdat %>% 
  select(FLUCCS17, FLUCCS90, Acres) %>% 
  group_by(FLUCCS17, FLUCCS90) %>% 
  summarise(Acres = sum(Acres)) %>% 
  ungroup %>% 
  mutate(
    FLUCCS17 = factor(FLUCCS17, levels = lkup$FLUCCSCODE),
    FLUCCS17 = fct_recode(FLUCCS17, !!!clp),
    FLUCCS90 = factor(FLUCCS90, levels = lkup$FLUCCSCODE),
    FLUCCS90 = fct_recode(FLUCCS90, !!!clp),
  ) %>% 
  na.omit() %>% 
  group_by(FLUCCS17, FLUCCS90) %>% 
  summarise(Acres = sum(Acres)) %>% 
  ungroup %>% 
  select(source = FLUCCS90, target = FLUCCS17, value = Acres) %>% 
  data.frame(stringsAsFactors = F)
sumdat$target <- paste(sumdat$target, " ", sep="")

# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes <- data.frame(name=c(as.character(sumdat$source), as.character(sumdat$target)) %>% unique())

# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
sumdat$IDsource=match(sumdat$source, nodes$name)-1 
sumdat$IDtarget=match(sumdat$target, nodes$name)-1

sankeyNetwork(Links = sumdat, Nodes = nodes,
              Source = "IDsource", Target = "IDtarget",
              Value = "value", NodeID = "name", height = 1200, width = 800,
              sinksRight=FALSE, units = 'acres', nodeWidth=40, fontSize=13, nodePadding=5)

```

## Class

```{r}
# format results
sums <- dat %>%
  filter(var %in% 'HMPU_CLASS') %>% 
  select(-var) %>% 
  spread(name, areaac, fill = NA) %>% 
  mutate(
    grpval = case_when(
      val %in% c('Agriculture', 'Mining', 'Urban') ~ 'Developed', 
      val %in% c('Emergent Tidal Wetlands', 'Freshwater Wetlands', 'Native Forested Uplands', 'Native Non-Forested Uplands') ~ 'Native'
    ), 
    chg = `2017` - `1990`,
    chgper = 100 * (`2017` - `1990`) / `1990`
  )

rct_fun(sums, 'Class')
```

## Group

```{r}
# format results
sums <- dat %>%
  filter(var %in% 'HMPU_GROUP') %>% 
  select(-var) %>% 
  spread(name, areaac, fill = NA) %>% 
  mutate(
    chg = `2017` - `1990`,
    chgper = 100 * (`2017` - `1990`) / `1990`
  )

rct_fun(sums, 'Group', grpby = F)
```

